/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fields
         * @description Return every persisted field with its descriptive attributes (003-R2).
         */
        get: operations["list_fields_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/{npdid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Field
         * @description Return one field's frozen ``Field``; 404 + ``field_not_found`` if the NPDID is absent (003-R2, R6).
         */
        get: operations["get_field_fields__npdid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/{npdid}/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Production
         * @description Return a field's full monthly history, ordered (year, month), nulls preserved (003-R3, R6).
         */
        get: operations["get_production_fields__npdid__production_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/{npdid}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forecast
         * @description Return the field's ``FieldForecast``; 404 distinguishes no-forecast from no-field (003-R4, R6).
         */
        get: operations["get_forecast_fields__npdid__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fields Geojson
         * @description Return the fields as a GeoJSON FeatureCollection; null-outline fields kept as null geometry (003-R5).
         */
        get: operations["fields_geojson_fields_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorCode
         * @description Machine-readable reason on an error response — lets 004 branch without parsing prose.
         * @enum {string}
         */
        ErrorCode: "field_not_found" | "forecast_not_available";
        /**
         * ErrorResponse
         * @description Typed error body returned with every 4xx (003-R6, and the R4 insufficient-history 404).
         */
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail: string;
        };
        /**
         * Field
         * @description A single NCS field: identity, descriptive attributes, outline geometry as WKT (R5, R7).
         */
        Field: {
            /** Field Npdid */
            field_npdid: number;
            /** Field Name */
            field_name: string;
            /** Current Activity Status */
            current_activity_status?: string | null;
            /** Hc Type */
            hc_type?: string | null;
            /** Main Area */
            main_area?: string | null;
            /** Operator */
            operator?: string | null;
            /** Discovery Year */
            discovery_year?: number | null;
            /** Geometry Wkt */
            geometry_wkt?: string | null;
        };
        /**
         * FieldFeature
         * @description One GeoJSON Feature: a field's outline (or null) + its identity (003-R5).
         */
        FieldFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["FieldProperties"];
        };
        /**
         * FieldFeatureCollection
         * @description The fields as a GeoJSON FeatureCollection (003-R5) — the Leaflet map source for 004.
         */
        FieldFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["FieldFeature"][];
        };
        /**
         * FieldForecast
         * @description A field's 24-month oil-equivalents forecast: selection, backtest, credibility (R1–R4, R7).
         */
        FieldForecast: {
            /** Field Npdid */
            field_npdid: number;
            /** @default oil_equivalents */
            target: components["schemas"]["ForecastTarget"];
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
            method: components["schemas"]["ForecastMethod"];
            /** Backtest Mape */
            backtest_mape: number;
            /** Credible */
            credible: boolean;
            /** History Months */
            history_months: number;
        };
        /**
         * FieldListResponse
         * @description The field list (003-R2) — every persisted Field with its descriptive attributes.
         */
        FieldListResponse: {
            /** Count */
            count: number;
            /** Fields */
            fields: components["schemas"]["Field"][];
        };
        /**
         * FieldProperties
         * @description A GeoJSON feature's properties for a field (003-R5) — identity only, for the map layer.
         */
        FieldProperties: {
            /** Field Npdid */
            field_npdid: number;
            /** Field Name */
            field_name: string;
        };
        /**
         * ForecastMethod
         * @description Which approach produced a forecast — the selected one is recorded on FieldForecast (R2).
         * @enum {string}
         */
        ForecastMethod: "arps_decline" | "holt_damped";
        /**
         * ForecastPoint
         * @description One forecasted oil-equivalents value for one calendar month (R1).
         */
        ForecastPoint: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Value */
            value: number;
        };
        /**
         * ForecastTarget
         * @description The forecast quantity. Fixed to oil-equivalents this cycle (spec §Scope; R1).
         * @enum {string}
         */
        ForecastTarget: "oil_equivalents";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MonthlyProduction
         * @description A single field-month production row, normalized from SODIR field_production_monthly (R4, R6).
         */
        MonthlyProduction: {
            /** Field Npdid */
            field_npdid: number;
            /** Field Name */
            field_name: string;
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Oil */
            oil?: number | null;
            /** Gas */
            gas?: number | null;
            /** Ngl */
            ngl?: number | null;
            /** Condensate */
            condensate?: number | null;
            /** Oil Equivalents */
            oil_equivalents?: number | null;
            /** Produced Water */
            produced_water?: number | null;
        };
        /**
         * ProductionHistoryResponse
         * @description A field's full monthly-production history (003-R3), ordered (year, month), nulls preserved.
         */
        ProductionHistoryResponse: {
            /** Field Npdid */
            field_npdid: number;
            /** Count */
            count: number;
            /** Production */
            production: components["schemas"]["MonthlyProduction"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_fields_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldListResponse"];
                };
            };
        };
    };
    get_field_fields__npdid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                npdid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_fields__npdid__production_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                npdid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionHistoryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_fields__npdid__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                npdid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldForecast"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fields_geojson_fields_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldFeatureCollection"];
                };
            };
        };
    };
}
